export const breadCrumbTitle: { [key: string]: string } = {
	abort: "Xuất hủy tinh",
	activity: "Hoạt động",
	add: "Thêm mới",
	area: "Khu",
	branMedicine: "Cám thuốc",
	breedInfo: "Thông tin lên giống",
	breedList: "Thiết lập mã giống",
	breedPoint: "Điểm phối giống",
	breeds: "Thiết lập giống",
	breedSelect: "Chọn giống",
	breedStandard: "Tiêu chuẩn chọn giống",
	breedState: "Trạng thái lên giống",
	breedSystem: "Hệ thống giống",
	breedWork: "Công tác giống",
	castrate: "Thiến heo",
	declare: "Thiết lập",
	dispose: "Xuất hủy heo",
	disease: "Thiết lập bệnh và lâm sàng",
	endBatch: "Vệ sinh nhà, kết thúc đợt",
	exploit: "Khai thác tinh",
	external: "Bên ngoài",
	externalSperm: "Tinh ngoài hệ thống",
	externalPigs: "Heo ngoài hệ thống",
	farm: "Thiết lập trại",
	farrow: "Thông tin đẻ",
	food: "Cám",
	foodProgram: "Chương trình cám",
	healthCondition: "Hiện trạng sức khỏe",
	healthEvaluate: "Cập nhật heo vấn đề các khu",
	home: "Trang chủ",
	insemination: "Thông tin phối",
	internalExport: "Xuất heo trại nội bộ",
	internalTransfer: "Chuyển nội bộ",
	management: "Quản lý heo",
	medicine: "Thuốc",
	medicineProgram: "Chương trình thuốc",
	origin: "Xuất xứ ngoài hệ thống",
	pigCode: "Mã cá thể",
	pigGender: "Giới tính heo",
	pigGroup: "Mã nhóm",
	pigProductivity: "Tính năng sản xuất",
	pigs: "Nhập liệu heo",
	pigsStandard: "Tiêu chuẩn đàn",
	pigState: "Hiện trạng heo",
	pigType: "Phân loại sản phẩm",
	pregnancy: "Heo mang thai",
	relocation: "Chuyển heo trong trại",
	role: "Phân quyền",
	salePlan: "Đăng ký heo lên khu 8",
	sperm: "Quản lý tinh",
	spermType: "Loại tinh",
	status: "Thiết lập trạng thái",
	statusPoint: "Điểm thể trạng",
	supplier: "Thiết lập nhà cung cấp",
	system: "Thiết lập hệ thống",
	technicalStandard: "Tiêu chuẩn kỹ thuật chăn nuôi",
	transfer: "Chuyển",
	unit: "Thiết lập đơn vị tính",
	userManagement: "Thiết lập người dùng",
	warehouse: "Thiết lập kho",
	weaning: "Cai sữa heo nái",
	geneticStandard: "Tiêu chuẩn đánh giá di truyền",
	externalGroup: "Heo nhóm ngoài hệ thống",
	problemStatus: "Hiện trạng vấn đề",
	reportPig: "Báo cáo heo",
	content: "Nội dung",
	activities: "Quản lý hoạt động chăn nuôi",
	reportData: "Báo cáo dữ liệu",
	managePig: "Quản lý heo",
	reportFarmOverall: "Tổng thể trại",
	reportSystemOverall: "Tổng thể hệ thống",
	reportQuarantine: "Khu cách ly",
	reportBoar: "Khu nọc",
	reportMating: "Khu phối",
	reportPregnancy: "Khu mang thai",
	reportFarrow: "Khu đẻ",
	reportWeaning: "Khu cai sữa",
	reportGilt: "Khu hậu bị",
	purchaseBran: "Quản lý mua hàng cám",
	utilizeBran: "Quản lý sử dụng cám",
	utilizeMedicine: "Quản lý sử dụng thuốc, vaccine",
	purchaseMedicine: "Quản lý mua hàng thuốc, vaccine",
	branUtilize: "Quản lí sử dụng cám",
	expectFarmBran: "Trại dự kiến cám sử dụng",
	planPurchaseBran: "Lập kế hoạch mua cám",
	business: "Thiết lập kinh doanh",
	customer: "Khách hàng",
	pigProduct: "Sản phẩm",
	sellExport: "Xuất bán heo",
	importFoodWarehouse: "Nhập kho mua hàng cám",
	orderBran: "Lập đơn hàng đặt cám",
	listPig: "Danh sách heo",
	group: "Heo nhóm",
	exportBranUtilize: "Xuất kho sử dụng cám",
	transferBran: "Xuất chuyển kho cám",
	exportReturnBran: "Xuất trả hàng cám",
	disposeBran: "Xuất hủy cám",
	exportUtilizeVaccine: "Xuất kho sử dụng vaccine",
	exportUtilizeMedicine: "Xuất kho sử dụng thuốc",
	transferMedicine: "Xuất chuyển kho thuốc",
	exportReturnMedicine: "Xuất trả hàng thuốc",
	disposeMedicine: "Xuất hủy thuốc",
	expectFarmMedicine: "Trại dự kiến thuốc, vaccine sử dụng",
	importMedicineWarehouse: "Nhập kho mua hàng thuốc",
	orderMedicine: "Lập đơn hàng đặt thuốc",
	planPurchaseMedicine: "Lập kế hoạch mua thuốc",
	buyer: "Người mua hàng",
	reportFarmSow: "Báo cáo năng suất trại nái",
	reportFarmWeaning: "Báo cáo năng suất Trại cai sữa - hậu bị",
	reportBranMedicine: "Báo cáo cám thuốc",
	reportUtilizeBran: "Báo cáo sử dụng cám",
	reportPurchaseBranProcedure: "Quy trình mua hàng cám",
	reportPurchaseBran: "Báo cáo mua hàng cám",
	reportPurchaseMedicineProcedure: "Quy trình mua hàng thuốc",
	reportPurchaseMedicine: "Báo cáo mua hàng thuốc",
	reportUtilizeMedicine: "Báo cáo sử dụng thuốc",
	utilizeMaterial: "Quản lý sử dụng vật liệu",
	transferMaterial: "Xuất chuyển vật liệu",
	disposeMeterial: "Xuất hủy vật liệu",
	exportReturnMaterial: "Xuất trả vật liệu",
	reportProductivity: "Báo cáo năng suất",
	importWarehouseMedicine: "Nhập kho mua hàng thuốc",
	disposeMaterial: "Xuất hủy vật liệu",
	internalTruck: "Thiết lập xe vận chuyển",
	licensePlate: "Danh mục xe vận chuyển",
	productivityNorm: "Định mức năng suất",
	productivityResult: "Tổng hợp năng suất",
	productivityDetailResult: "Chi tiết năng suất",
	sowQualified: "Nái đủ ĐKSX-TT.QM",
	breedGenetic: "Báo cáo giống di truyền",
	edit: "Cập nhập",
	exportImport: "Quản lý nhập xuất heo",
	externalImport: "Nhập heo ngoài hệ thống",
	externalTransfer: "Xuất heo trại nội bộ",
	earResources: "Tài nguyên số tai",
	reportBran: "Báo cáo cám",
	reportMedicine: "Báo cáo thuốc",
	weightStandard: "Tiêu chuẩn cân nặng",
	otherMaterialImport: "Nhập khác",
	otherMaterialExport: "Xuất khác",
	product: "Sản phẩm",
	manage: "Quản lý nhập liệu",
	order: "Nhập liệu đơn hàng",
	customerGroup: "Nhóm khách hàng",
	customerType: "Loại khách hàng",
	priceSetting: "Thiết lập giá bán",
	productGroup: "Nhóm sản phẩm",
	deliveryFarm: "Đơn vị giao",
	declareCustomer: "Thiết lập khách hàng",
	managePrice: "Nhập liệu giá",
	HTPrice: "Giá heo thịt",
	pigletPrice: "Giá heo con",
	giltPrice: "Giá heo hậu bị",
	cullPrice: "Giá heo loại",
	problemDocument: "Biên bản ghi nhận và xử lí vấn đề",
	sellPig: "Lệnh xuất bán",
	billing: "Phiếu tính tiền",
	report: "Báo cáo",
	weighingActivity: "Báo cáo hoạt động cân heo",
	productionActivityDetail: "Chi tiết nhập xuất tồn",
	productionActivity: "Tổng hợp nhập xuất tồn",
	truckScale: "Chi tiết cân xe",
	cageScaleByDetail: "Chi tiết cân lồng theo lần cân",
	cageScaleByTicket: "Chi tiết cân lồng theo phiếu cân",
	sellPigByCustomer: "Xuất bán theo khách hàng",
	compareImportAndSale: "So sánh từ nhập trại đến xuất heo",
	compareSellScale: "So sánh cân xuất bán",
	bankAccount: "Tài khoản ngân hàng",
	exportToTs: "Xuất heo qua TTC",
};
